function(check_target_link_qt target)
    set(QT_CORE_LIBRARY Qt6::Core)

    get_target_property(LINKED_LIBRARIES ${target} LINK_LIBRARIES)

    if(LINKED_LIBRARIES)
        list(FIND LINKED_LIBRARIES ${QT_CORE_LIBRARY} lib_index)
        if(lib_index GREATER -1)
            message(STATUS "${target} links to ${QT_CORE_LIBRARY}")
            set(${target}_links_qt TRUE PARENT_SCOPE)
        else()
            message(STATUS "${target} does not link to ${QT_CORE_LIBRARY}")
            set(${target}_links_qt FALSE PARENT_SCOPE)
        endif()
    else()
        message(STATUS "${target} does not have any linked libraries.")
        set(${target}_links_qt FALSE PARENT_SCOPE)
    endif()
endfunction()